version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: civicpulse-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: civicpulse-backend
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/civicpulse
      - JWT_SECRET=civicpulse_secret_jwt_key_2026_super_secure
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    container_name: civicpulse-frontend
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    depends_on:
      - backend

volumes:
  mongo_data:
